In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

df = pd.read_csv("../data/processed/laptop_selected.csv")
df

,Brand,Series,Thickness,Weight,Operating System,Display Size,Display Touchscreen,Processor,Graphic Processor,RAM_Capacity_GB,RAM Type,SSD Capacity,HDD Capacity,Battery Capacity,Fingerprint scanner,Price (Rs)
0,HP,Pavilion,17.0,1.41,Windows 10 Home Basic,14.0,No,intel core i5-1135g7 (11th gen),intel iris x,16.0,DDR4,512.0,NaN,NaN,No,71990.0
1,Acer,Predator Helios Neo 16,26.5,2.60,Windows 11 Home Basic,16.0,No,intel core i7-13700hx (13th gen),nvidia geforce rtx 4050,16.0,DDR5,512.0,NaN,NaN,NaN,105999.0
2,Dell,Inspiron 15,22.7,2.20,Windows 10 Home Basic,15.6,No,intel core i5-8250u (8th gen),amd radeon 530,8.0,DDR4,NaN,2.0,NaN,No,54999.0
3,MSI,NaN,29.0,2.20,DOS,15.6,No,intel core i7-7700hq (7th gen),nvidia geforce gtx 1050,8.0,DDR4,NaN,1.0,NaN,No,67990.0
4,Dell,Inspiron 15,23.0,1.80,Windows 11 Home Basic,15.6,No,amd dual core athlon 3050u,amd radeon,4.0,DDR4,256.0,NaN,NaN,NaN,42210.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8073,Acer,ConceptD,17.9,2.10,Windows 10 Home Basic,15.6,No,intel core i7-9750h (9th gen),nvidia geforce rtx 2080,32.0,DDR4,1.0,NaN,NaN,No,260999.0
8074,Acer,ConceptD,17.9,2.10,Windows 10 Home Basic,15.6,No,intel core i7-9750h (9th gen),nvidia geforce rtx 2080,32.0,DDR4,512.0,NaN,NaN,No,255999.0
8075,Lenovo,Thinkpad,17.0,1.22,Windows 10 Professional,13.3,No,intel core i5-10210u (10th gen),intel uhd,8.0,DDR4,512.0,NaN,NaN,No,115900.0
8076,Lenovo,Thinkpad,21.0,1.77,DOS,14.0,No,intel core i5-10210u (10th gen),intel uhd,8.0,DDR4,256.0,NaN,NaN,No,59073.0
8077,Lenovo,Legion,26.0,2.30,Windows 10 Home Basic,15.6,No,intel core i7-9750h (9th gen),nvidia geforce gtx 1650,16.0,DDR4,512.0,NaN,NaN,No,105999.0

In [2]:
X = df.drop(columns=["Price (Rs)"])
y = df["Price (Rs)"]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [4]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (6462, 15)
X_test : (1616, 15)
y_train: (6462,)
y_test : (1616,)

In [5]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 6462 entries, 2487 to 7270
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Brand                6462 non-null   str
 1   Series               5579 non-null   str
 2   Thickness            5916 non-null   float64
 3   Weight               6232 non-null   float64
 4   Operating System     6462 non-null   str
 5   Display Size         6460 non-null   float64
 6   Display Touchscreen  6399 non-null   str
 7   Processor            6462 non-null   str
 8   Graphic Processor    6399 non-null   str
 9   RAM_Capacity_GB      6462 non-null   float64
 10  RAM Type             6351 non-null   str
 11  SSD Capacity         5394 non-null   float64
 12  HDD Capacity         1466 non-null   float64
 13  Battery Capacity     1896 non-null   float64
 14  Fingerprint scanner  4343 non-null   str
dtypes: float64(7), str(8)
memory usage: 807.8 KB

In [7]:
X_train.isna().sum()

Brand                     0
Series                  883
Thickness               546
Weight                  230
Operating System          0
Display Size              2
Display Touchscreen      63
Processor                 0
Graphic Processor        63
RAM_Capacity_GB           0
RAM Type                111
SSD Capacity           1068
HDD Capacity           4996
Battery Capacity       4566
Fingerprint scanner    2119
dtype: int64

In [8]:
numerical_features = [
    "Thickness",
    "Weight",
    "Display Size",
    "RAM_Capacity_GB",
    "SSD Capacity",
    "HDD Capacity",
    "Battery Capacity"
]

categorical_features = [
    "Brand",
    "Series",
    "Operating System",
    "Display Touchscreen",
    "Processor",
    "Graphic Processor",
    "RAM Type",
    "Fingerprint scanner"
]

In [9]:
print("Numerical features:")
print(X_train[numerical_features].dtypes)

print("\nCategorical features:")
print(X_train[categorical_features].dtypes)

Numerical features:
Thickness           float64
Weight              float64
Display Size        float64
RAM_Capacity_GB     float64
SSD Capacity        float64
HDD Capacity        float64
Battery Capacity    float64
dtype: object

Categorical features:
Brand                  str
Series                 str
Operating System       str
Display Touchscreen    str
Processor              str
Graphic Processor      str
RAM Type               str
Fingerprint scanner    str
dtype: object

In [ ]:
print("Total features:", len(X_train.columns))
print("Numerical features:", len(numerical_features))
print("Categorical features:", len(categorical_features))

Total features: 15
Numerical features: 7
Categorical features: 8
All features accounted for: True

In [11]:
numerical_missing = pd.DataFrame({
    "Missing Count": X_train[numerical_features].isna().sum(),
    "Missing Percentage": (
        X_train[numerical_features].isna().mean() * 100
    ).round(2)
}).sort_values("Missing Percentage", ascending=False)

numerical_missing

                  Missing Count  Missing Percentage
HDD Capacity               4996               77.31
Battery Capacity           4566               70.66
SSD Capacity               1068               16.53
Thickness                   546                8.45
Weight                      230                3.56
Display Size                  2                0.03
RAM_Capacity_GB               0                0.00

In [13]:
categorical_missing = pd.DataFrame({
    "Missing Count": X_train[categorical_features].isna().sum(),
    "Missing Percentage": (
        X_train[categorical_features].isna().mean() * 100
    ).round(2),
    "Unique values":X_train[categorical_features].nunique()
}).sort_values("Missing Percentage", ascending=False)

categorical_missing

                     Missing Count  Missing Percentage  Unique values
Fingerprint scanner           2119               32.79              5
Series                         883               13.66            503
RAM Type                       111                1.72             10
Display Touchscreen             63                0.97              2
Graphic Processor               63                0.97            313
Brand                            0                0.00             35
Operating System                 0                0.00             32
Processor                        0                0.00            677

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [16]:
numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [17]:
numerical_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [22]:
from sklearn.preprocessing import OneHotEncoder
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [23]:
categorical_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [24]:
X_train_cat = categorical_pipeline.fit_transform(
    X_train[categorical_features]
)

In [26]:
encoded_feature_names = categorical_pipeline.named_steps[
    "encoder"
].get_feature_names_out(categorical_features)

print("Number of encoded features:", len(encoded_feature_names))
print("\nFirst 20 encoded features:")
print(encoded_feature_names[:20])

Number of encoded features: 1577

First 20 encoded features:
['Brand_Acer' 'Brand_Apple' 'Brand_Asus' 'Brand_Avita' 'Brand_Coconics'
 'Brand_Colorful' 'Brand_Dell' 'Brand_Fujitsu' 'Brand_Gigabyte' 'Brand_HP'
 'Brand_Honor' 'Brand_Huawei' 'Brand_Infinix' 'Brand_LG' 'Brand_Lava'
 'Brand_Lenovo' 'Brand_MSI' 'Brand_Micromax' 'Brand_Microsoft'
 'Brand_Motorola']

In [27]:
from sklearn.compose import ColumnTransformer

In [28]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_pipeline, numerical_features),
        ("cat", categorical_pipeline, categorical_features)
    ]
)

In [29]:
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['Thickness', 'Weight', 'Display Size',
                                  'RAM_Capacity_GB', 'SSD Capacity',
                                  'HDD Capacity', 'Battery Capacity']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Brand', 'Series', 'Operating System',
                                  'Display Touchscreen', 'Processor',
                                  'Graphic Processor', 'RAM Type',
                                  'Fingerprint scanner'])])

In [30]:
print("Numerical columns:")
print(preprocessor.transformers[0][2])

print("\nCategorical columns:")
print(preprocessor.transformers[1][2])

Numerical columns:
['Thickness', 'Weight', 'Display Size', 'RAM_Capacity_GB', 'SSD Capacity', 'HDD Capacity', 'Battery Capacity']

Categorical columns:
['Brand', 'Series', 'Operating System', 'Display Touchscreen', 'Processor', 'Graphic Processor', 'RAM Type', 'Fingerprint scanner']

In [ ]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [46]:

print("Training transformed shape:", X_train_transformed.shape)
print("Testing transformed shape:", X_test_transformed.shape)

Training transformed shape: (6462, 1584)
Testing transformed shape: (1616, 1584)

In [44]:
categorical_encoder_fitted = (
    preprocessor
    .named_transformers_["cat"]
    .named_steps["encoder"]
)

print("Number of categorical features:")
print(len(categorical_encoder_fitted.categories_))

print("\nCategories learned for each categorical feature:")
for feature, categories in zip(
    categorical_features,
    categorical_encoder_fitted.categories_
):
    print(f"{feature}: {len(categories)} categories")

Number of categorical features:
8

Categories learned for each categorical feature:
Brand: 35 categories
Series: 503 categories
Operating System: 32 categories
Display Touchscreen: 2 categories
Processor: 677 categories
Graphic Processor: 313 categories
RAM Type: 10 categories
Fingerprint scanner: 5 categories

In [43]:
print(type(preprocessor))

<class 'sklearn.compose._column_transformer.ColumnTransformer'>